DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ibl_v2_app')
     AND NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ibl_v2_api') THEN
    GRANT USAGE ON SCHEMA public TO ibl_v2_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ibl_v2_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ibl_v2_app;
    GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO ibl_v2_app;
    ALTER DEFAULT PRIVILEGES FOR ROLE ibl_v2_migration IN SCHEMA public
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ibl_v2_app;
    ALTER DEFAULT PRIVILEGES FOR ROLE ibl_v2_migration IN SCHEMA public
      GRANT USAGE, SELECT ON SEQUENCES TO ibl_v2_app;
    ALTER DEFAULT PRIVILEGES FOR ROLE ibl_v2_migration IN SCHEMA public
      GRANT EXECUTE ON FUNCTIONS TO ibl_v2_app;
  END IF;
END
$$;
