export const FOLLOW_UP_UTC_CLOCK = "(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')";

export const FOLLOW_UP_CLAIM_SQL = [
	'UPDATE "followUpStep"',
	`SET "status"='LEASED', "leaseOwner"=$1, "leasedUntil"=${FOLLOW_UP_UTC_CLOCK}+INTERVAL '60 seconds', "attemptCount"="attemptCount"+1, "updatedAt"=${FOLLOW_UP_UTC_CLOCK}`,
	'WHERE "id"=(',
	'  SELECT s."id" FROM "followUpStep" s',
	'  JOIN "followUpPlan" p ON p."id"=s."planId"',
	"  WHERE s.\"status\" IN ('PENDING','LEASED')",
	"    AND p.\"status\"='ACTIVE'",
	`    AND s."dueAt"<=${FOLLOW_UP_UTC_CLOCK}`,
	`    AND (s."retryAt" IS NULL OR s."retryAt"<=${FOLLOW_UP_UTC_CLOCK})`,
	`    AND (s."leasedUntil" IS NULL OR s."leasedUntil"<=${FOLLOW_UP_UTC_CLOCK})`,
	'    AND s."attemptCount"<s."maxAttempts"',
	"    AND (p.\"channel\"<>'EMAIL' OR (",
	`      (EXISTS (SELECT 1 FROM "providerCapability" pc WHERE pc."key"='RESEND_OUTBOUND' AND pc."status"='VERIFIED') OR $2::boolean)`,
	'      AND EXISTS (SELECT 1 FROM "draft" d WHERE d."id"=s."draftId" AND (',
	`        (d."status"='APPROVED' AND EXISTS (SELECT 1 FROM "outreachApproval" oa WHERE oa."draftId"=d."id" AND oa."status"='APPROVED'))`,
	`        OR (d."status"='DRAFT' AND d."coldOutreach"=true AND $3::boolean AND EXISTS (SELECT 1 FROM "mailbox" m WHERE m."id"=d."mailboxId" AND lower(m."address")='outreach@iblmedia.com') AND EXISTS (SELECT 1 FROM "appSetting" a WHERE a."id"='app' AND a."atlasLiveOutreachEnabled"=true) AND EXISTS (SELECT 1 FROM "outreachAuthorization" a WHERE a."id"=d."authorizationId" AND a."scope"='STANDARD_COLD_OUTREACH' AND a."status"='ACTIVE' AND a."followUpCohortId"=$4::text AND (a."expiresAt" IS NULL OR a."expiresAt">${FOLLOW_UP_UTC_CLOCK}) AND EXISTS (SELECT 1 FROM "followUpExecutionCohort" c JOIN "followUpExecutionCohortMember" m ON m."cohortId"=c."id" WHERE c."id"=a."followUpCohortId" AND c."state"='ACTIVE' AND m."followUpStepId"=s."id" AND m."status"='PENDING' AND m."canonicalDueAt"<=${FOLLOW_UP_UTC_CLOCK})))`,
	"      ))",
	"    ))",
	'  ORDER BY s."dueAt",s."id" FOR UPDATE OF s SKIP LOCKED LIMIT 1',
	")",
	'RETURNING "id","planId","draftId","attemptCount"',
].join("\n");

export const FOLLOW_UP_COHORT_CLAIM_SQL = [
	"WITH candidate AS (",
	'  SELECT s."id",m."cohortId" FROM "followUpStep" s',
	'  JOIN "followUpPlan" p ON p."id"=s."planId"',
	'  JOIN "followUpExecutionCohortMember" m ON m."followUpStepId"=s."id"',
	'  JOIN "followUpExecutionCohort" c ON c."id"=m."cohortId"',
	'  JOIN "outreachAuthorization" a ON a."followUpCohortId"=c."id"',
	'  JOIN "draft" d ON d."id"=s."draftId"',
	'  WHERE m."cohortId"=$2::text AND c."state"=\'ACTIVE\' AND m."status"=\'PENDING\'',
	"    AND s.\"status\" IN ('PENDING','LEASED') AND p.\"status\"='ACTIVE' AND p.\"channel\"='EMAIL'",
	`    AND s."dueAt"<=${FOLLOW_UP_UTC_CLOCK} AND m."canonicalDueAt"<=${FOLLOW_UP_UTC_CLOCK}`,
	`    AND (s."retryAt" IS NULL OR s."retryAt"<=${FOLLOW_UP_UTC_CLOCK})`,
	`    AND (s."leasedUntil" IS NULL OR s."leasedUntil"<=${FOLLOW_UP_UTC_CLOCK})`,
	'    AND s."attemptCount"<s."maxAttempts" AND d."status"=\'DRAFT\' AND d."coldOutreach"=true',
	'    AND a."scope"=\'STANDARD_COLD_OUTREACH\' AND a."status"=\'ACTIVE\' AND (a."expiresAt" IS NULL OR a."expiresAt">' +
		FOLLOW_UP_UTC_CLOCK +
		")",
	'    AND $3::boolean AND EXISTS (SELECT 1 FROM "appSetting" settings WHERE settings."id"=\'app\' AND settings."atlasLiveOutreachEnabled"=true)',
	'    AND ($4::boolean OR EXISTS (SELECT 1 FROM "providerCapability" pc WHERE pc."key"=\'RESEND_OUTBOUND\' AND pc."status"=\'VERIFIED\'))',
	'    AND EXISTS (SELECT 1 FROM "mailbox" mailbox WHERE mailbox."id"=d."mailboxId" AND lower(mailbox."address")=\'outreach@iblmedia.com\')',
	'  ORDER BY m."canonicalDueAt",s."id" FOR UPDATE OF s SKIP LOCKED LIMIT 1',
	"), claimed AS (",
	'  UPDATE "followUpStep" s SET "status"=\'LEASED\',"leaseOwner"=$1,',
	`    "leasedUntil"=${FOLLOW_UP_UTC_CLOCK}+INTERVAL '60 seconds',`,
	`    "attemptCount"=s."attemptCount"+1,"updatedAt"=${FOLLOW_UP_UTC_CLOCK}`,
	'  FROM candidate c WHERE s."id"=c."id"',
	'  RETURNING s."id",s."planId",s."draftId",s."attemptCount"',
	') SELECT claimed."id",claimed."planId",claimed."draftId",claimed."attemptCount",candidate."cohortId"',
	'FROM claimed JOIN candidate ON candidate."id"=claimed."id"',
].join("\n");
